import type { ContenuBrut } from "../app/_content/schemas";

// Produits du fichier 13 §2 pour le Maroc. Conformité, composition, minimum et délai : à saisir
// depuis les certificats et les devis. Tant que la conformité manque, statut « brouillon ».

export const produits = [
  {
    id: "savon-noir",
    nom: "Savon noir (beldi)",
    categorie: "cosmetique",
    usage: "Hammam : savon noir en pot ou en grand format pour les hammams et spas d’hôtels et les riads",
    segments: ["hotels", "spas"],
    formats: ["pot", "grand-format-pro"],
    composition: "[À COMPLÉTER : composition telle qu’elle figure sur l’étiquette]",
    conformite: "[À COMPLÉTER : numéro d’enregistrement DMP et date d’expiration du certificat]",
    personnalisations: ["etiquette", "couleurs", "langue", "texte-libre"],
    minimumCommande: "[À COMPLÉTER : minimum de commande]",
    delai: "[À COMPLÉTER : délai de fabrication et de livraison]",
    statut: "brouillon",
  },
  {
    id: "ghassoul",
    nom: "Ghassoul en poudre",
    categorie: "cosmetique",
    usage: "Hammam : ghassoul en poudre pour les hammams et spas",
    segments: ["hotels", "spas"],
    formats: ["grand-format-pro"],
    composition: "[À COMPLÉTER : composition telle qu’elle figure sur l’étiquette]",
    conformite: "[À COMPLÉTER : numéro d’enregistrement DMP et date d’expiration du certificat]",
    personnalisations: ["etiquette", "couleurs", "langue", "texte-libre"],
    minimumCommande: "[À COMPLÉTER : minimum de commande]",
    delai: "[À COMPLÉTER : délai de fabrication et de livraison]",
    statut: "brouillon",
  },
  {
    id: "gant-kessa",
    nom: "Gant de kessa",
    categorie: "accessoire",
    usage: "Hammam : gant utilisé avec le savon noir",
    segments: ["hotels", "spas"],
    formats: "[À COMPLÉTER : formats (gant de kessa)]",
    composition: "[À COMPLÉTER : composition telle qu’elle figure sur l’étiquette]",
    conformite: "[À COMPLÉTER : statut réglementaire d’un accessoire (ni DMP ni ONSSA)]",
    personnalisations: ["etiquette", "couleurs", "langue", "texte-libre"],
    minimumCommande: "[À COMPLÉTER : minimum de commande]",
    delai: "[À COMPLÉTER : délai de fabrication et de livraison]",
    statut: "brouillon",
  },
  {
    id: "huile-argan",
    nom: "Huile d’argan",
    categorie: "cosmetique",
    usage: "Huile pure pour le visage et les cheveux : salles de bain et boutiques d’hôtels, spas, cadeaux",
    segments: ["hotels", "spas", "cadeaux"],
    formats: ["flacon", "grand-format-pro"],
    composition: "[À COMPLÉTER : composition telle qu’elle figure sur l’étiquette]",
    conformite: "[À COMPLÉTER : numéro d’enregistrement DMP et date d’expiration du certificat]",
    personnalisations: ["etiquette", "boite", "couleurs", "langue", "texte-libre"],
    minimumCommande: "[À COMPLÉTER : minimum de commande]",
    delai: "[À COMPLÉTER : délai de fabrication et de livraison]",
    statut: "brouillon",
  },
  {
    id: "gel-douche-argan",
    nom: "Gel douche à l’argan",
    categorie: "cosmetique",
    usage: "Produit d’accueil en recharge pour les salles de bain d’hôtels",
    segments: ["hotels"],
    formats: ["recharge-5l"],
    composition: "[À COMPLÉTER : composition telle qu’elle figure sur l’étiquette]",
    conformite: "[À COMPLÉTER : numéro d’enregistrement DMP et date d’expiration du certificat]",
    personnalisations: ["etiquette", "couleurs", "langue", "texte-libre"],
    minimumCommande: "[À COMPLÉTER : minimum de commande]",
    delai: "[À COMPLÉTER : délai de fabrication et de livraison]",
    statut: "brouillon",
  },
  {
    id: "shampoing-argan",
    nom: "Shampoing à l’argan",
    categorie: "cosmetique",
    usage: "Produit d’accueil en recharge pour les salles de bain d’hôtels",
    segments: ["hotels"],
    formats: ["recharge-5l"],
    composition: "[À COMPLÉTER : composition telle qu’elle figure sur l’étiquette]",
    conformite: "[À COMPLÉTER : numéro d’enregistrement DMP et date d’expiration du certificat]",
    personnalisations: ["etiquette", "couleurs", "langue", "texte-libre"],
    minimumCommande: "[À COMPLÉTER : minimum de commande]",
    delai: "[À COMPLÉTER : délai de fabrication et de livraison]",
    statut: "brouillon",
  },
  {
    id: "eau-fleur-oranger",
    nom: "Eau de fleur d’oranger",
    categorie: "cosmetique",
    usage: "Brume, tonique ou eau d’accueil parfumée : chambres, spas, cadeaux de bienvenue",
    segments: ["hotels", "spas", "cadeaux"],
    formats: "[À COMPLÉTER : formats (eau de fleur d’oranger)]",
    composition: "[À COMPLÉTER : composition telle qu’elle figure sur l’étiquette]",
    conformite: "[À COMPLÉTER : numéro d’enregistrement DMP et date d’expiration du certificat]",
    personnalisations: ["etiquette", "boite", "couleurs", "langue", "texte-libre"],
    minimumCommande: "[À COMPLÉTER : minimum de commande]",
    delai: "[À COMPLÉTER : délai de fabrication et de livraison]",
    statut: "brouillon",
  },
  {
    id: "savon-solide-argan",
    nom: "Savon solide à l’argan",
    categorie: "cosmetique",
    usage: "Savon sans emballage plastique pour les salles de bain d’hôtels et les cadeaux",
    segments: ["hotels", "cadeaux"],
    formats: "[À COMPLÉTER : formats (savon solide à l’argan)]",
    composition: "[À COMPLÉTER : composition telle qu’elle figure sur l’étiquette]",
    conformite: "[À COMPLÉTER : numéro d’enregistrement DMP et date d’expiration du certificat]",
    personnalisations: ["etiquette", "boite", "couleurs", "langue", "texte-libre"],
    minimumCommande: "[À COMPLÉTER : minimum de commande]",
    delai: "[À COMPLÉTER : délai de fabrication et de livraison]",
    statut: "brouillon",
  },
  {
    id: "savon-solide-ghassoul",
    nom: "Savon solide au ghassoul",
    categorie: "cosmetique",
    usage: "Savon sans emballage plastique pour les salles de bain d’hôtels et les cadeaux",
    segments: ["hotels", "cadeaux"],
    formats: "[À COMPLÉTER : formats (savon solide au ghassoul)]",
    composition: "[À COMPLÉTER : composition telle qu’elle figure sur l’étiquette]",
    conformite: "[À COMPLÉTER : numéro d’enregistrement DMP et date d’expiration du certificat]",
    personnalisations: ["etiquette", "boite", "couleurs", "langue", "texte-libre"],
    minimumCommande: "[À COMPLÉTER : minimum de commande]",
    delai: "[À COMPLÉTER : délai de fabrication et de livraison]",
    statut: "brouillon",
  },
  {
    id: "savon-solide-fleur-oranger",
    nom: "Savon solide à la fleur d’oranger",
    categorie: "cosmetique",
    usage: "Savon sans emballage plastique pour les salles de bain d’hôtels et les cadeaux",
    segments: ["hotels", "cadeaux"],
    formats: "[À COMPLÉTER : formats (savon solide à la fleur d’oranger)]",
    composition: "[À COMPLÉTER : composition telle qu’elle figure sur l’étiquette]",
    conformite: "[À COMPLÉTER : numéro d’enregistrement DMP et date d’expiration du certificat]",
    personnalisations: ["etiquette", "boite", "couleurs", "langue", "texte-libre"],
    minimumCommande: "[À COMPLÉTER : minimum de commande]",
    delai: "[À COMPLÉTER : délai de fabrication et de livraison]",
    statut: "brouillon",
  },
  {
    id: "huile-olive-du-verger",
    nom: "Huile d’olive du verger",
    categorie: "alimentaire",
    usage: "Bouteille personnalisée ou coffret dégustation : restaurants d’hôtels, cadeaux d’entreprise",
    segments: ["hotels", "cadeaux"],
    formats: ["bouteille", "boite"],
    composition: "[À COMPLÉTER : composition telle qu’elle figure sur l’étiquette]",
    conformite: "[À COMPLÉTER : numéro d’autorisation ONSSA du conditionneur et date d’expiration]",
    personnalisations: ["etiquette", "boite", "couleurs", "langue", "texte-libre"],
    minimumCommande: "[À COMPLÉTER : minimum de commande]",
    delai: "[À COMPLÉTER : délai de fabrication et de livraison]",
    statut: "brouillon",
  },
  {
    id: "coffret-gourmand",
    nom: "Coffret gourmand (safran, amlou, miel, thé)",
    categorie: "alimentaire",
    usage: "Cadeaux de bienvenue, cadeaux d’entreprise, mariages",
    segments: ["hotels", "cadeaux"],
    formats: ["boite"],
    composition: "[À COMPLÉTER : composition telle qu’elle figure sur l’étiquette]",
    conformite: "[À COMPLÉTER : numéro d’autorisation ONSSA du conditionneur et date d’expiration]",
    personnalisations: ["etiquette", "boite", "couleurs", "langue", "texte-libre"],
    minimumCommande: "[À COMPLÉTER : minimum de commande]",
    delai: "[À COMPLÉTER : délai de fabrication et de livraison]",
    statut: "brouillon",
  },
] satisfies ContenuBrut["produits"];
